/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocales_consonantes;

/**
 *
 * @author juanj
 */
public class EvTeclas extends javax.swing.JFrame {

    /**
     * Creates new form EvTeclas
     */
    public EvTeclas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcaja1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Letras Escritas ");

        txtcaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaja1ActionPerformed(evt);
            }
        });
        txtcaja1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaja1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcaja1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int contador;
    int consonantes;
    private void txtcaja1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaja1KeyReleased
        
        
        
        // obtenemos el valor que escriven en la interfaz 
       String sPalabra =txtcaja1.getText();
        // con este for recorremos la palabra 
        for(int x=0;x<sPalabra.length();x++) {
            // las condicionales comparan cuantas vocales o consonantes tiene la palabra 
        if ((sPalabra.charAt(x)=='a') || (sPalabra.charAt(x)=='e') || (sPalabra.charAt(x)=='i') || (sPalabra.charAt(x)=='o') || (sPalabra.charAt(x)=='u')){ 
              contador++;
  }
            if ((sPalabra.charAt(x)=='b') || (sPalabra.charAt(x)=='c') || (sPalabra.charAt(x)=='d') || (sPalabra.charAt(x)=='f') || (sPalabra.charAt(x)=='g')|| (sPalabra.charAt(x)=='h')|| (sPalabra.charAt(x)=='j')|| (sPalabra.charAt(x)=='k')|| (sPalabra.charAt(x)=='l')|| (sPalabra.charAt(x)=='m')
                    || (sPalabra.charAt(x)=='n')|| (sPalabra.charAt(x)=='ñ')|| (sPalabra.charAt(x)=='p')|| (sPalabra.charAt(x)=='q')|| (sPalabra.charAt(x)=='r')|| (sPalabra.charAt(x)=='s')|| (sPalabra.charAt(x)=='t')|| (sPalabra.charAt(x)=='v')|| (sPalabra.charAt(x)=='x')|| (sPalabra.charAt(x)=='z')|| (sPalabra.charAt(x)=='w')) {
                consonantes++;
            }
            if ((sPalabra.charAt(x)=='A') || (sPalabra.charAt(x)=='E') || (sPalabra.charAt(x)=='I') || (sPalabra.charAt(x)=='O') || (sPalabra.charAt(x)=='U')) {
                
                contador++;
            }if ((sPalabra.charAt(x)=='B') || (sPalabra.charAt(x)=='C') || (sPalabra.charAt(x)=='D') || (sPalabra.charAt(x)=='F') || (sPalabra.charAt(x)=='G')|| (sPalabra.charAt(x)=='H')|| (sPalabra.charAt(x)=='J')|| (sPalabra.charAt(x)=='K')|| (sPalabra.charAt(x)=='L')|| (sPalabra.charAt(x)=='M')
                    || (sPalabra.charAt(x)=='N')|| (sPalabra.charAt(x)=='Ñ')|| (sPalabra.charAt(x)=='P')|| (sPalabra.charAt(x)=='Q')|| (sPalabra.charAt(x)=='R')|| (sPalabra.charAt(x)=='S')|| (sPalabra.charAt(x)=='T')|| (sPalabra.charAt(x)=='V')|| (sPalabra.charAt(x)=='X')|| (sPalabra.charAt(x)=='Z')|| (sPalabra.charAt(x)=='W')) {
                consonantes++;
            }
            
        }  
        //obtenemos el valor y se lo asignamos ala variable Palabra
            String Palabra =txtcaja1.getText();
            //al ingresar una palabra lo comparara con los casos y si no esta mostrara incorrecto
            switch(Palabra){
                
                case "lunes": jLabel4.setText("correcto");;
                break;
                case "martes": jLabel4.setText("correcto");;
                 break;
                case "miercoles": jLabel4.setText("correcto");;
                 break;
                case "jueves": jLabel4.setText("correcto");;
                 break;
                 case "viernes": jLabel4.setText("correcto");;
                 break;
                case "sabado": jLabel4.setText("correcto");;
                 break;
                case "domingo": jLabel4.setText("correcto");;
                 break;
                case "": jLabel4.setText("Incorrecto");;
            }
        
        // imprime las vocales y consonantes en pantalla
        jLabel2.setText("La palabra " +" "+ sPalabra +" "+ "contiene " + contador + " vocales"+" "+"Consonantes"+consonantes);
        contador =0;
        consonantes=0;
    }//GEN-LAST:event_txtcaja1KeyReleased

    private void txtcaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaja1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvTeclas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvTeclas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvTeclas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvTeclas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvTeclas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcaja1;
    // End of variables declaration//GEN-END:variables
}
